// <auto-generated />
using System;
using InvoiceRobot.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InvoiceRobot.Infrastructure.Migrations
{
    [DbContext(typeof(InvoiceRobotDbContext))]
    partial class InvoiceRobotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InvoiceRobot.Core.Domain.ApprovalRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovedProjectKey")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("InvoiceId")
                        .HasColumnType("int");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RespondedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("SentAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("InvoiceId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("Token")
                        .IsUnique();

                    b.ToTable("ApprovalRequests");
                });

            modelBuilder.Entity("InvoiceRobot.Core.Domain.Invoice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("AiAnalyzedAt")
                        .HasColumnType("datetime2");

                    b.Property<double?>("AiConfidenceScore")
                        .HasColumnType("float");

                    b.Property<string>("AiReasoning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DueDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FinalProjectKey")
                        .HasColumnType("int");

                    b.Property<int?>("HeuristicProjectKey")
                        .HasColumnType("int");

                    b.Property<string>("HeuristicReasoning")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("HeuristicScore")
                        .HasColumnType("float");

                    b.Property<DateTime>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("NetvisorInvoiceKey")
                        .HasColumnType("int");

                    b.Property<DateTime?>("OcrProcessedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("OcrText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PdfData")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PdfUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<int?>("SuggestedProjectKey")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedToAccountingSystemAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("VendorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("FinalProjectKey");

                    b.HasIndex("InvoiceNumber");

                    b.HasIndex("NetvisorInvoiceKey")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("SuggestedProjectKey");

                    b.ToTable("Invoices");
                });

            modelBuilder.Entity("InvoiceRobot.Core.Domain.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("NetvisorProjectKey")
                        .HasColumnType("int");

                    b.Property<string>("ProjectCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ProjectManagerEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NetvisorProjectKey")
                        .IsUnique();

                    b.HasIndex("ProjectCode")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("InvoiceRobot.Core.Domain.ApprovalRequest", b =>
                {
                    b.HasOne("InvoiceRobot.Core.Domain.Invoice", "Invoice")
                        .WithOne("ApprovalRequest")
                        .HasForeignKey("InvoiceRobot.Core.Domain.ApprovalRequest", "InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("InvoiceRobot.Core.Domain.Invoice", b =>
                {
                    b.HasOne("InvoiceRobot.Core.Domain.Project", "FinalProject")
                        .WithMany("FinalInvoices")
                        .HasForeignKey("FinalProjectKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("InvoiceRobot.Core.Domain.Project", "SuggestedProject")
                        .WithMany("SuggestedInvoices")
                        .HasForeignKey("SuggestedProjectKey")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("FinalProject");

                    b.Navigation("SuggestedProject");
                });

            modelBuilder.Entity("InvoiceRobot.Core.Domain.Invoice", b =>
                {
                    b.Navigation("ApprovalRequest");
                });

            modelBuilder.Entity("InvoiceRobot.Core.Domain.Project", b =>
                {
                    b.Navigation("FinalInvoices");

                    b.Navigation("SuggestedInvoices");
                });
#pragma warning restore 612, 618
        }
    }
}
